language: erlang

os: linux
otp_release:
  - 21.0

script:
  - ./rebar3 compile
  - ./rebar3 xref
  - ./rebar3 eunit
  - ./rebar3 dialyzer
  - ./rebar3 edoc
  - ./rebar3 cover
  - DEBUG=1 ./rebar3 as test covertool generate
